name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    
    - name: Build the C# code
      run: dotnet build  

    - name: Run the C# tests
      run: dotnet test      
    
    - name: Build the TypeScript code
      run: npm install && npm run build
      working-directory: ./DotnetTemplate.Web

    - name: Run the linter on the TypeScript code
      run: npm t
      working-directory: ./DotnetTemplate.Web

    - name: Run the TypeScript tests
      run: npm install && npm run build
      working-directory: ./DotnetTemplate.Web