name: Continuous Integration
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    
    - name: Build the C# code
      run: dotnet build  

    - name: Run the C# tests
      run: dotnet test      
    
    - name: Build the TypeScript code
      run: npm install && npm run build
      working-directory: ./DotnetTemplate.Web

    - name: Run the linter on the TypeScript code
      run: npm run lint
      working-directory: ./DotnetTemplate.Web

    - name: Run the TypeScript tests
      run: npm t
      working-directory: ./DotnetTemplate.Web

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Docker Login
    # You may pin to the exact commit or the version.
    # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    uses: docker/login-action@v1.10.0
    with:     
      # Username used to log against the Docker registry
      username: ${{secrets.DOCKER_USER}}
      # Password or personal access token used to log against the Docker registry
      password: ${{secrets.DOCKER_PASSWORD}}
    run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  
      